### ISSUE TITLE
Dockerfile no longer builds

### ISSUE THREAD

**Issue by jtfogarty** [gashirar/theia-kubernetes#2]
I'm wanting to modify your dockerfile to add Jenkins-x and gcloud.
I started by simply building your dockerfile but it fails in the below go module
```github.com/josharian/impl```
It does build after I comment out that line but when I attempt to run it, I get the below;
```
docker run -it -p 3000:3000 -v "$(pwd):/home/project:cached" gashirar/theia-jx:0.0
yarn run v1.9.4
$ /home/theia/node_modules/.bin/theia start /home/project --hostname=0.0.0.0
Failed to start the backend application.
{ Error: Cannot find module '@theia/git/lib/node/init/git-init-module'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/theia/src-gen/backend/server.js:66:48
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3 code: 'MODULE_NOT_FOUND' }
/home/theia/node_modules/@theia/core/lib/node/main.js:56
    throw reason;
    ^

Error: Cannot find module '@theia/git/lib/node/init/git-init-module'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /home/theia/src-gen/backend/server.js:66:48
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Done in 1.28s.
```
Any ideas?
Thanks

**Comment by gashirar** [comment]
@jtfogarty 
I made some changes. Would you be able to build?

**Comment by jtfogarty** [comment]
@gashirar Yes, that builds. Thanks!!
